simplify init scripts by exiting/returning early
all init scripts now look the same and can probably be merged into one,
if needed.

diff --git a/templates/consumer.init.erb b/templates/consumer.init.erb
--- a/templates/consumer.init.erb
+++ b/templates/consumer.init.erb
@@ -21,6 +21,7 @@
 NAME=kafka-consumer
 PID_FILE=/var/run/$NAME.pid
 KAFKA_USER=kafka
+PGREP_PATTERN=kafka.tools.ConsoleConsumer
 
 DAEMON="/opt/kafka/bin/kafka-console-consumer.sh"
 DAEMON_OPTS="<% @consumer_service_config.sort.each do |k,v| -%><% unless v.to_s.strip.empty? -%>--<%= k -%>=<%= v.is_a?(Array) ? v.join(',') : v %> <% end -%><% end -%>"
@@ -33,29 +34,29 @@ if [ -f /etc/default/kafka ]; then
 fi
 
 start() {
-  if [ -f $PID_FILE ]
-    then
+  if [ -f $PID_FILE ]; then
       PID=`cat $PID_FILE`
-      if [ -z "`ps -ef | awk '{print $2}' | grep "^$PID$"`" ]; then
+      if `ps -p "$PID" -o pid= ` -eq `pgrep -f "$PGREP_PATTERN"`; then
         echo "\n$PID_FILE exists, process is already running"
         exit 0
-      else
-        echo "\n$PID_FILE exists but the process is not running. Deleting $PID_FILE and re-trying"
-        rm -f $PID_FILE
-        start
       fi
-    else
-        /bin/su $KAFKA_USER -c "$DAEMON $DAEMON_OPTS >> /var/log/kafka/consumer.log 2>&1 &"
-        sleep 2
-        PID=`pgrep -f kafka.tools.ConsoleConsumer`
-        if [ -z "$PID" ]; then
-            echo "\n $NAME could not be started"
-            exit 1
-        else
-            echo $PID > $PID_FILE;
-            echo "\n$NAME started"
-        fi
-    fi
+
+      echo "\n$PID_FILE exists but the process is not running. Deleting $PID_FILE and re-trying"
+      rm -f $PID_FILE
+      start
+      return $?
+  fi
+
+  /bin/su $KAFKA_USER -c "$DAEMON $DAEMON_OPTS >> /var/log/kafka/consumer.log 2>&1 &"
+  sleep 2
+  PID=`pgrep -f "$PGREP_PATTERN"`
+  if [ -z "$PID" ]; then
+    echo "\n $NAME could not be started"
+    exit 1
+  fi
+
+  echo $PID > $PID_FILE;
+  echo "\n$NAME started"
 }
 
 stop() {
@@ -72,21 +73,19 @@ stop() {
 }
 
 status() {
-  if [ -f $PID_FILE ]
-  then
-    PID=`cat $PID_FILE`
-    if [ -z "`ps -ef | awk '{print $2}' | grep "^$PID$"`" ]
-    then
-      echo "$NAME stopped but pid file exists"
-      exit 1
-    else
-      echo "$NAME running with pid $PID"
-      exit 0
-    fi
-  else
+  if [ ! -f $PID_FILE ]; then
     echo "$NAME stopped"
     exit 1
   fi
+
+  PID=`cat $PID_FILE`
+  if `ps -p "$PID" -o pid= ` -eq `pgrep -f "$PGREP_PATTERN"`; then
+    echo "$NAME stopped but pid file exists"
+    exit 1
+  fi
+
+  echo "$NAME running with pid $PID"
+  exit 0
 }
 
 case "$1" in
diff --git a/templates/mirror.init.erb b/templates/mirror.init.erb
--- a/templates/mirror.init.erb
+++ b/templates/mirror.init.erb
@@ -21,6 +21,7 @@
 NAME=kafka-mirror
 PID_FILE=/var/run/$NAME.pid
 KAFKA_USER=kafka
+PGREP_PATTERN=kafka.tools.MirrorMaker
 
 DAEMON="/opt/kafka/bin/kafka-run-class.sh"
 DAEMON_OPTS="kafka.tools.MirrorMaker --consumer.config <%= @consumer_config -%> --num.streams <%= @num_streams -%> --producer.config <%= @producer_config -%><%- if (scope.function_versioncmp([scope.lookupvar('kafka::version'), '0.9.0.0']) < 0) -%> --num.producers <%= @num_producers -%><%- end -%><%- if !@whitelist.eql?('') -%> --whitelist='<%= @whitelist -%>'<%- end %><%- if !@blacklist.eql?('') -%> --blacklist='<%= @blacklist -%>'<%- end -%>"
@@ -37,60 +38,58 @@ start() {
   ulimit -n 65536
   ulimit -s 10240
   ulimit -c unlimited
-  if [ -f $PID_FILE ]
-  then
+  if [ -f $PID_FILE ]; then
     PID=`cat $PID_FILE`
-    if [ -z "`ps -ef | awk '{print $2}' | grep "^$PID$"`" ]; then
+    if `ps -p "$PID" -o pid= ` -eq `pgrep -f "$PGREP_PATTERN"`; then
       echo "\n$PID_FILE exists, process is already running"
       exit 0
-    else
-      echo "\n$PID_FILE exists but the process is not running. Deleting $PID_FILE and re-trying"
-      rm -f $PID_FILE
-      start
     fi
-  else
-    /bin/su $KAFKA_USER -c "$DAEMON $DAEMON_OPTS >> /var/log/kafka/mirror.log 2>&1 &"
-    sleep 2
-    PID=`pgrep -f kafka.tools.MirrorMaker`
-    if [ -z "$PID" ]; then
-        echo "\n $NAME could not be started"
-        exit 1
-    else
-        echo $PID > $PID_FILE;
-        echo "\n$NAME started"
-    fi
+
+    echo "\n$PID_FILE exists but the process is not running. Deleting $PID_FILE and re-trying"
+    rm -f $PID_FILE
+
+    start
+    return $?
   fi
+
+  /bin/su $KAFKA_USER -c "$DAEMON $DAEMON_OPTS >> /var/log/kafka/mirror.log 2>&1 &"
+  sleep 2
+  PID=`pgrep -f "$PGREP_PATTERN"`
+  if [ -z "$PID" ]; then
+    echo "\n $NAME could not be started"
+    exit 1
+  fi
+
+  echo $PID > $PID_FILE;
+  echo "\n$NAME started"
 }
 
 stop() {
-  if [ ! -f $PID_FILE ]
-  then
+  if [ ! -f $PID_FILE ]; then
     echo "\n$PID_FILE does not exist, process is not running"
     return 1
-  else
-    kill `cat $PID_FILE`;
-    rm -f $PID_FILE;
-    echo "\n$NAME stopped"
-    return 0
   fi
+
+  kill `cat $PID_FILE`;
+  rm -f $PID_FILE;
+  echo "\n$NAME stopped"
+  return 0
 }
 
 status() {
-  if [ -f $PID_FILE ]
-  then
-    PID=`cat $PID_FILE`
-    if [ -z "`ps -ef | awk '{print $2}' | grep "^$PID$"`" ]
-    then
-      echo "$NAME stopped but pid file exists"
-      exit 1
-    else
-      echo "$NAME running with pid $PID"
-      exit 0
-    fi
-  else
+  if [ ! -f $PID_FILE ]; then
     echo "$NAME stopped"
     exit 1
   fi
+
+  PID=`cat $PID_FILE`
+  if `ps -p "$PID" -o pid= ` -eq `pgrep -f "$PGREP_PATTERN"`; then
+    echo "$NAME stopped but pid file exists"
+    exit 1
+  fi
+
+  echo "$NAME running with pid $PID"
+  exit 0
 }
 
 case "$1" in
