Fix empty PID file creation on failed daemon start

diff --git a/templates/mirror.init.erb b/templates/mirror.init.erb
--- a/templates/mirror.init.erb
+++ b/templates/mirror.init.erb
@@ -25,8 +25,13 @@ start() {
     exec $DAEMON $DAEMON_OPTS >> /var/log/kafka/mirror.log 2>&1 &
     sleep 2
     PID=`ps ax | grep -E '[k]afka.tools.MirrorMaker' | awk '{print $1}'`
-    echo $PID > $PID_FILE;
-    echo "\n$NAME started"
+    if [ -z "$PID" ]; then
+        echo "\n $NAME could not be started"
+        exit 1
+    else
+        echo $PID > $PID_FILE;
+        echo "\n$NAME started"
+    fi
   fi
 }
 
